<template>
  <BaseModal
    :model-value="show"
    title="Report Details"
    size="xl"
    @update:model-value="$emit('update:show', $event)"
  >
    <div class="space-y-8">
      <!-- Report Information -->
      <section>
        <h3 class="text-lg font-medium text-gray-900 mb-4">Report Information</h3>
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <div>
            <label class="text-sm font-medium text-gray-500">Name</label>
            <p class="mt-1">{{ report.name }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">Type</label>
            <p class="mt-1">
              <span
                :class="[
                  'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium',
                  typeClasses[report.type] || ''
                ]"
              >
                {{ report.type }}
              </span>
            </p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">Category</label>
            <p class="mt-1">{{ report.category }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">Generated By</label>
            <p class="mt-1">{{ report.generated_by_name }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">Generated At</label>
            <p class="mt-1">{{ formatDate(report.generated_at) }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">Format</label>
            <p class="mt-1">{{ report.format.toUpperCase() }}</p>
          </div>
          <div class="sm:col-span-2 lg:col-span-3">
            <label class="text-sm font-medium text-gray-500">Description</label>
            <p class="mt-1">{{ report.description || 'No description provided' }}</p>
          </div>
        </div>
      </section>

      <!-- Date Range -->
      <section>
        <h3 class="text-lg font-medium text-gray-900 mb-4">Date Range</h3>
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <label class="text-sm font-medium text-gray-500">Start Date</label>
            <p class="mt-1">{{ formatDate(report.start_date) }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-500">End Date</label>
            <p class="mt-1">{{ formatDate(report.end_date) }}</p>
          </div>
        </div>
      </section>

      <!-- Filters -->
      <section>
        <h3 class="text-lg font-medium text-gray-900 mb-4">Applied Filters</h3>
        <div class="bg-gray-50 rounded-lg p-4">
          <dl class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <template v-for="(value, key) in report.filters" :key="key">
              <div>
                <dt class="text-sm font-medium text-gray-500">{{ formatFilterKey(key) }}</dt>
                <dd class="mt-1 text-sm text-gray-900">{{ formatFilterValue(key, value) }}</dd>
              </div>
            </template>
          </dl>
        </div>
      </section>

      <!-- Preview -->
      <section>
        <h3 class="text-lg font-medium text-gray-900 mb-4">Preview</h3>
        <div class="bg-gray-50 rounded-lg p-4">
          <!-- PDF Preview -->
          <template v-if="report.format === 'pdf' && report.preview_url">
            <iframe
              :src="report.preview_url"
              class="w-full h-[600px] border-0 rounded"
              title="PDF Preview"
            ></iframe>
          </template>

          <!-- Excel/CSV Preview -->
          <template v-else-if="['xlsx', 'csv'].includes(report.format) && report.preview_data">
            <div class="overflow-x-auto">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th
                      v-for="header in report.preview_data.headers"
                      :key="header"
                      class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                    >
                      {{ header }}
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <tr
                    v-for="(row, index) in report.preview_data.rows"
                    :key="index"
                  >
                    <td
                      v-for="(cell, cellIndex) in row"
                      :key="cellIndex"
                      class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                    >
                      {{ cell }}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </template>

          <!-- No Preview -->
          <template v-else>
            <div class="text-center py-12">
              <svg
                class="mx-auto h-12 w-12 text-gray-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
              </svg>
              <h3 class="mt-2 text-sm font-medium text-gray-900">No preview available</h3>
              <p class="mt-1 text-sm text-gray-500">
                Please download the report to view its contents.
              </p>
              <div class="mt-6">
                <BaseButton
                  variant="primary"
                  @click="downloadReport"
                >
                  Download Report
                </BaseButton>
              </div>
            </div>
          </template>
        </div>
      </section>
    </div>

    <!-- Modal Footer -->
    <template #footer>
      <div class="flex justify-end space-x-3">
        <BaseButton
          variant="secondary"
          @click="downloadReport"
        >
          Download
        </BaseButton>
        <BaseButton
          variant="secondary"
          @click="$emit('update:show', false)"
        >
          Close
        </BaseButton>
      </div>
    </template>
  </BaseModal>
</template>

<script>
import { useToast } from '@/composables/useToast'
import { useApi } from '@/composables/useApi'

export default {
  name: 'ReportViewer',

  props: {
    show: {
      type: Boolean,
      required: true
    },
    report: {
      type: Object,
      required: true
    }
  },

  emits: ['update:show'],

  setup(props) {
    const { showToast } = useToast()
    const api = useApi()

    const typeClasses = {
      asset: 'bg-blue-100 text-blue-800',
      maintenance: 'bg-green-100 text-green-800',
      work_order: 'bg-yellow-100 text-yellow-800',
      cost: 'bg-purple-100 text-purple-800',
      performance: 'bg-red-100 text-red-800'
    }

    const downloadReport = async () => {
      try {
        const response = await api.get(`/api/reports/${props.report.id}/download`, {
          responseType: 'blob'
        })

        const url = window.URL.createObjectURL(new Blob([response.data]))
        const link = document.createElement('a')
        link.href = url
        link.setAttribute('download', props.report.name)
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
      } catch (error) {
        showToast('Error downloading report', 'error')
      }
    }

    const formatDate = (date) => {
      if (!date) return ''
      return new Date(date).toLocaleDateString()
    }

    const formatFilterKey = (key) => {
      return key
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ')
    }

    const formatFilterValue = (key, value) => {
      if (value === 'all') return 'All'
      if (key === 'assigned_to') {
        return props.report.assigned_to_name || value
      }
      return value
    }

    return {
      typeClasses,
      downloadReport,
      formatDate,
      formatFilterKey,
      formatFilterValue
    }
  }
}
</script> 